### ISSUE TITLE
assertion failure in generic-array

### ISSUE THREAD

**Issue by ggutoski** [RustCrypto/elliptic-curves#323]
Clone the following repo https://github.com/ggutoski/k256_test and run `cargo test` a few times until the test fails.  Output:
```
thread 'tests::k256' panicked at 'assertion failed: `(left == right)`
  left: `31`,
 right: `32`', /Users/gus/.cargo/registry/src/github.com-1ecc6299db9ec823/generic-array-0.14.4/src/lib.rs:559:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   2: <&generic_array::GenericArray<T,N> as core::convert::From<&[T]>>::from
             at /Users/gus/.cargo/registry/src/github.com-1ecc6299db9ec823/generic-array-0.14.4/src/lib.rs:559:9
   3: <T as core::convert::Into<U>>::into
             at /Users/gus/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/convert/mod.rs:539:9
   4: generic_array::GenericArray<T,N>::from_slice
             at /Users/gus/.cargo/registry/src/github.com-1ecc6299db9ec823/generic-array-0.14.4/src/lib.rs:541:9
   5: k256_test::tests::k256
             at ./src/main.rs:50:19
   6: k256_test::tests::k256::{{closure}}
             at ./src/main.rs:26:5
   7: core::ops::function::FnOnce::call_once
             at /Users/gus/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test tests::k256 ... FAILED
```
This test creates ECDSA signatures in another library and then imports into k256 via `FieldBytes::from_slice`.  I don't know whether it's possible to trigger this failure using only k256.  ~My guess is the only problem in k256 is that arguments passed to `from_slice` are not properly sanitized.~

**EDIT:** It might be my fault for giving malformed bytes.  Is there a helper function to sanitize bytes before giving them to `FieldBytes::from_slice`?

**Comment by tarcieri** [comment]
The failing stack frames show:

```
   4: generic_array::GenericArray<T,N>::from_slice
             at /Users/gus/.cargo/registry/src/github.com-1ecc6299db9ec823/generic-array-0.14.4/src/lib.rs:541:9
   5: k256_test::tests::k256
             at ./src/main.rs:50:19
```

The lines of code in question are:

```
            let (r, s): (FieldBytes, FieldBytes) =
                (*FieldBytes::from_slice(r), *FieldBytes::from_slice(s));
```

This suggests that either `r` or `s` are smaller than 64-bytes. The [`GenericArray::from_slice`](https://docs.rs/generic-array/0.14.4/generic_array/struct.GenericArray.html#method.from_slice) method will panic if the input is not exactly 64-bytes (in this particular instance, anyway).

`r` and `s` are both elements of the scalar field, serialized as big endian integers. As such, if they are smaller than 64-bytes, you'll need to zero-pad them to 64-bytes. Something like:

```rust
fn pad_field_element(slice: &[u8; 64]) -> FieldBytes {
    assert!(slice.len() < 64); // or perhaps make the return type `Option<FieldBytes>` and return `None`

    let mut fe_bytes = FieldBytes::default();
    fe_bytes[(64 - slice.len())..].copy_from_slice(slice);
    fe_bytes
}
```
